apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-server-ci
  name: go-server-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server-ci
  template:
    metadata:
      labels:
        app: go-server-ci
    spec:
      containers:
      - image: ghcr.io/2023-4400-exp/4413-go-server-ci:c8fd969c8ff0d0a563044c772757f77ad80b06db@sha256:586d1a145780515ca53b5945cf13f6a80ed3b847d1fc0167843cf5cb26c1f0a0
        name: go-server-ci
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-server-ci
  name: go-server-ci
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-server-ci
  type: NodePort
